// <auto-generated />
using Car.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car.API.Migrations
{
    [DbContext(typeof(CarInfoDbContext))]
    [Migration("20250127171759_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Car.API.Models.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_mark")
                        .HasComment("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name_rus");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TypeId" }, "id_car_type");

                    b.ToTable("car_mark", null, t =>
                        {
                            t.HasComment("Марки автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_characteristic")
                        .HasComment("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("id_parent");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type1");

                    b.HasIndex(new[] { "Name", "ParentId", "TypeId" }, "name");

                    b.ToTable("car_characteristic", null, t =>
                        {
                            t.HasComment("Характеристики автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarCharacteristicValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_characteristic_value");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_characteristic");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<int>("ModificationId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_modification");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("unit")
                        .HasComment("Еденица измерения");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CharacteristicId", "ModificationId", "TypeId" }, "id_car_characteristic")
                        .IsUnique();

                    b.HasIndex(new[] { "TypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type2");

                    b.HasIndex(new[] { "CharacteristicId", "ModificationId" }, "id_characteristic")
                        .IsUnique();

                    b.ToTable("car_characteristic_value", null, t =>
                        {
                            t.HasComment("Значения характеристик автомобиля");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_color")
                        .HasComment("ID цвета");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название цвета");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_color", null, t =>
                        {
                            t.HasComment("Цвета автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_condition")
                        .HasComment("ID состояния авто");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название состояния");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_condition", null, t =>
                        {
                            t.HasComment("Состояние автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_equipment")
                        .HasComment("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<int>("ModificationId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_modification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PriceMin")
                        .HasColumnType("int")
                        .HasColumnName("price_min")
                        .HasComment("Цена от");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TypeId" }, "date_delete");

                    b.ToTable("car_equipment", null, t =>
                        {
                            t.HasComment("Комплектации");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarExchangeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_exchange_option")
                        .HasComment("ID варианта обмена");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название варианта обмена");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_exchange_option", null, t =>
                        {
                            t.HasComment("Варианты обмена автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_generation");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<string>("YearBegin")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("year_begin");

                    b.Property<string>("YearEnd")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("year_end");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelId" }, "id_car_model");

                    b.HasIndex(new[] { "TypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type3");

                    b.ToTable("car_generation", null, t =>
                        {
                            t.HasComment("Поколения Моделей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarInteriorColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_interior_color")
                        .HasComment("ID цвета салона");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название цвета салона");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_interior_color", null, t =>
                        {
                            t.HasComment("Цвета салона автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarInteriorMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_interior_material")
                        .HasComment("ID материала салона");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название материала салона");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_interior_material", null, t =>
                        {
                            t.HasComment("Материалы салона автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_model")
                        .HasComment("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_mark");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name_rus");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BrandId" }, "id_car_mark");

                    b.HasIndex(new[] { "TypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type4");

                    b.HasIndex(new[] { "Name" }, "name")
                        .HasDatabaseName("name1");

                    b.ToTable("car_model", null, t =>
                        {
                            t.HasComment("Модели автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarModification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_modification")
                        .HasComment("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("SerieId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_serie");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelId" }, "id_car_model")
                        .HasDatabaseName("id_car_model1");

                    b.HasIndex(new[] { "SerieId" }, "id_car_serie");

                    b.HasIndex(new[] { "TypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type5");

                    b.ToTable("car_modification", null, t =>
                        {
                            t.HasComment("Модификации автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_option");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("id_parent");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type6");

                    b.ToTable("car_option", null, t =>
                        {
                            t.HasComment("Опции");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarOptionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_option_value");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_equipment");

                    b.Property<bool>("IsBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_base")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("OptionId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_option");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TypeId" }, "date_delete")
                        .HasDatabaseName("date_delete1");

                    b.HasIndex(new[] { "OptionId", "EquipmentId", "TypeId" }, "id_car_option")
                        .IsUnique();

                    b.ToTable("car_option_value", null, t =>
                        {
                            t.HasComment("Значения опций");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_serie")
                        .HasComment("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<int?>("GenerationId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_generation");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelId" }, "id_car_model")
                        .HasDatabaseName("id_car_model2");

                    b.HasIndex(new[] { "TypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type7");

                    b.HasIndex(new[] { "Name" }, "name")
                        .HasDatabaseName("name2");

                    b.ToTable("car_serie", null, t =>
                        {
                            t.HasComment("Cерии автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_type", null, t =>
                        {
                            t.HasComment("Автомобильный сайт");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
