// <auto-generated />
using Car.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car.API.Migrations
{
    [DbContext(typeof(CarInfoDbContext))]
    partial class CarInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Car.API.Models.CarBodyType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_body_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_body_type", (string)null);
                });

            modelBuilder.Entity("Car.API.Models.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_mark")
                        .HasComment("ID");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name_rus");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarTypeId" }, "id_car_type");

                    b.ToTable("car_mark", null, t =>
                        {
                            t.HasComment("Марки автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_characteristic")
                        .HasComment("id");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("id_parent");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ParentId" }, "fk_car_characteristic_id_parent");

                    b.HasIndex(new[] { "CarTypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type1");

                    b.HasIndex(new[] { "Name", "ParentId", "CarTypeId" }, "name");

                    b.ToTable("car_characteristic", null, t =>
                        {
                            t.HasComment("Характеристики автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarCharacteristicValue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_characteristic_value");

                    b.Property<int>("CarCharacteristicId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_characteristic");

                    b.Property<int>("CarModificationId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_modification");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("unit")
                        .HasComment("Еденица измерения");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarModificationId" }, "fk_car_characteristic_value_id_car_modification");

                    b.HasIndex(new[] { "CarCharacteristicId", "CarModificationId", "CarTypeId" }, "id_car_characteristic")
                        .IsUnique();

                    b.HasIndex(new[] { "CarTypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type2");

                    b.HasIndex(new[] { "CarCharacteristicId", "CarModificationId" }, "id_characteristic")
                        .IsUnique();

                    b.ToTable("car_characteristic_value", null, t =>
                        {
                            t.HasComment("Значения характеристик автомобиля");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_color")
                        .HasComment("ID цвета");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название цвета");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_color", null, t =>
                        {
                            t.HasComment("Цвета автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_condition")
                        .HasComment("ID состояния авто");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название состояния");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_condition", null, t =>
                        {
                            t.HasComment("Состояние автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarDriveType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_drive_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_drive_type", (string)null);
                });

            modelBuilder.Entity("Car.API.Models.CarEngineType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_engine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_engine_type", (string)null);
                });

            modelBuilder.Entity("Car.API.Models.CarEquipment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_equipment")
                        .HasComment("id");

                    b.Property<int>("CarModificationId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_modification");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PriceMin")
                        .HasColumnType("int")
                        .HasColumnName("price_min")
                        .HasComment("Цена от");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarTypeId" }, "date_delete");

                    b.HasIndex(new[] { "CarModificationId" }, "fk_car_equipment_id_car_modification");

                    b.ToTable("car_equipment", null, t =>
                        {
                            t.HasComment("Комплектации");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarExchangeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_exchange_option")
                        .HasComment("ID варианта обмена");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название варианта обмена");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_exchange_option", null, t =>
                        {
                            t.HasComment("Варианты обмена автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarGeneration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_generation");

                    b.Property<int>("CarModelId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_model");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("YearBegin")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("year_begin");

                    b.Property<string>("YearEnd")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("year_end");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarModelId" }, "id_car_model");

                    b.HasIndex(new[] { "CarTypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type3");

                    b.ToTable("car_generation", null, t =>
                        {
                            t.HasComment("Поколения Моделей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarInteriorColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_interior_color")
                        .HasComment("ID цвета салона");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название цвета салона");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_interior_color", null, t =>
                        {
                            t.HasComment("Цвета салона автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarInteriorMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_car_interior_material")
                        .HasComment("ID материала салона");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название материала салона");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_interior_material", null, t =>
                        {
                            t.HasComment("Материалы салона автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_model")
                        .HasComment("ID");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_mark");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameRus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name_rus");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarBrandId" }, "id_car_mark");

                    b.HasIndex(new[] { "CarTypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type4");

                    b.HasIndex(new[] { "Name" }, "name")
                        .HasDatabaseName("name1");

                    b.ToTable("car_model", null, t =>
                        {
                            t.HasComment("Модели автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarModification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_modification")
                        .HasComment("ID");

                    b.Property<int?>("CarDriveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_drive_type");

                    b.Property<int?>("CarEngineTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_engine_type");

                    b.Property<int>("CarModelId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_model");

                    b.Property<int>("CarSerieId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_serie");

                    b.Property<int?>("CarTransmissionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_transmission_type");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<int?>("EngineCapacity")
                        .HasColumnType("int")
                        .HasColumnName("engine_capacity");

                    b.Property<int?>("EnginePower")
                        .HasColumnType("int")
                        .HasColumnName("engine_power");

                    b.Property<decimal?>("FuelConsumptionCombined")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("fuel_consumption_combined");

                    b.Property<decimal?>("GroundClearance")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ground_clearance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarDriveTypeId" }, "id_car_drive_type");

                    b.HasIndex(new[] { "CarEngineTypeId" }, "id_car_engine_type");

                    b.HasIndex(new[] { "CarModelId" }, "id_car_model")
                        .HasDatabaseName("id_car_model1");

                    b.HasIndex(new[] { "CarSerieId" }, "id_car_serie");

                    b.HasIndex(new[] { "CarTransmissionTypeId" }, "id_car_transmission_type");

                    b.HasIndex(new[] { "CarTypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type5");

                    b.ToTable("car_modification", null, t =>
                        {
                            t.HasComment("Модификации автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarOption", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_option");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("id_parent");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ParentId" }, "fk_car_option_parent");

                    b.HasIndex(new[] { "CarTypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type6");

                    b.ToTable("car_option", null, t =>
                        {
                            t.HasComment("Опции");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarOptionValue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_option_value");

                    b.Property<int>("CarEquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_equipment");

                    b.Property<int>("CarOptionId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_option");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.Property<bool>("IsBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_base")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarTypeId" }, "date_delete")
                        .HasDatabaseName("date_delete1");

                    b.HasIndex(new[] { "CarEquipmentId" }, "fk_car_option_value_equipment");

                    b.HasIndex(new[] { "CarOptionId", "CarEquipmentId", "CarTypeId" }, "id_car_option")
                        .IsUnique();

                    b.ToTable("car_option_value", null, t =>
                        {
                            t.HasComment("Значения опций");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarSerie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_serie")
                        .HasComment("ID");

                    b.Property<int>("CarBodyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_body_type");

                    b.Property<int?>("CarGenerationId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_generation");

                    b.Property<int>("CarModelId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_model");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<uint?>("DateCreate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_create");

                    b.Property<uint?>("DateUpdate")
                        .HasColumnType("int unsigned")
                        .HasColumnName("date_update");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarGenerationId" }, "fk_car_generation_serie");

                    b.HasIndex(new[] { "CarBodyTypeId" }, "id_car_body_type");

                    b.HasIndex(new[] { "CarModelId" }, "id_car_model")
                        .HasDatabaseName("id_car_model2");

                    b.HasIndex(new[] { "CarTypeId" }, "id_car_type")
                        .HasDatabaseName("id_car_type7");

                    b.ToTable("car_serie", null, t =>
                        {
                            t.HasComment("Cерии автомобилей");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarTransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_transmission_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_transmission_type", (string)null);
                });

            modelBuilder.Entity("Car.API.Models.CarType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id_car_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_type", null, t =>
                        {
                            t.HasComment("Автомобильный сайт");
                        });
                });

            modelBuilder.Entity("Car.API.Models.CarBrand", b =>
                {
                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarBrands")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_mark_id_car_type");

                    b.Navigation("CarTypeNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarCharacteristic", b =>
                {
                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarCharacteristics")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_characteristic_id_car_type");

                    b.HasOne("Car.API.Models.CarCharacteristic", "ParentNavigation")
                        .WithMany("InverseParentNavigation")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_car_characteristic_id_parent");

                    b.Navigation("CarTypeNavigation");

                    b.Navigation("ParentNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarCharacteristicValue", b =>
                {
                    b.HasOne("Car.API.Models.CarCharacteristic", "CarCharacteristicNavigation")
                        .WithMany("CarCharacteristicValues")
                        .HasForeignKey("CarCharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_characteristic_value_id_car_characteristic");

                    b.HasOne("Car.API.Models.CarModification", "CarModificationNavigation")
                        .WithMany("CarCharacteristicValues")
                        .HasForeignKey("CarModificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_characteristic_value_id_car_modification");

                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarCharacteristicValues")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_characteristic_value_id_car_type");

                    b.Navigation("CarCharacteristicNavigation");

                    b.Navigation("CarModificationNavigation");

                    b.Navigation("CarTypeNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarEquipment", b =>
                {
                    b.HasOne("Car.API.Models.CarModification", "CarModificationNavigation")
                        .WithMany("CarEquipment")
                        .HasForeignKey("CarModificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_equipment_id_car_modification");

                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarEquipments")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_equipment_id_car_type");

                    b.Navigation("CarModificationNavigation");

                    b.Navigation("CarTypeNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarGeneration", b =>
                {
                    b.HasOne("Car.API.Models.CarModel", "CarModelNavigation")
                        .WithMany("CarGenerations")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_generation_id_car_model");

                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarGenerations")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_generation_id_car_type");

                    b.Navigation("CarModelNavigation");

                    b.Navigation("CarTypeNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarModel", b =>
                {
                    b.HasOne("Car.API.Models.CarBrand", "CarBrandNavigation")
                        .WithMany("CarModels")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_model_id_car_mark");

                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarModels")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_model_id_car_type");

                    b.Navigation("CarBrandNavigation");

                    b.Navigation("CarTypeNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarModification", b =>
                {
                    b.HasOne("Car.API.Models.CarDriveType", "CarDriveTypeNavigation")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarDriveTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_car_drive_type");

                    b.HasOne("Car.API.Models.CarEngineType", "CarEngineTypeNavigation")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarEngineTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_car_engine_type");

                    b.HasOne("Car.API.Models.CarModel", "CarModelNavigation")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_model");

                    b.HasOne("Car.API.Models.CarSerie", "CarSerieNavigation")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarSerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_serie");

                    b.HasOne("Car.API.Models.CarTransmissionType", "CarTransmissionTypeNavigation")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarTransmissionTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_car_transmission_type");

                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_type");

                    b.Navigation("CarDriveTypeNavigation");

                    b.Navigation("CarEngineTypeNavigation");

                    b.Navigation("CarModelNavigation");

                    b.Navigation("CarSerieNavigation");

                    b.Navigation("CarTransmissionTypeNavigation");

                    b.Navigation("CarTypeNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarOption", b =>
                {
                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarOptions")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_type_option");

                    b.HasOne("Car.API.Models.CarOption", "ParentNavigation")
                        .WithMany("InverseParentNavigation")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_car_option_parent");

                    b.Navigation("CarTypeNavigation");

                    b.Navigation("ParentNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarOptionValue", b =>
                {
                    b.HasOne("Car.API.Models.CarEquipment", "CarEquipmentNavigation")
                        .WithMany("CarOptionValues")
                        .HasForeignKey("CarEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_option_value_equipment");

                    b.HasOne("Car.API.Models.CarOption", "CarOptionNavigation")
                        .WithMany("CarOptionValues")
                        .HasForeignKey("CarOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_option_value_option");

                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarOptionValues")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_option_value_type");

                    b.Navigation("CarEquipmentNavigation");

                    b.Navigation("CarOptionNavigation");

                    b.Navigation("CarTypeNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarSerie", b =>
                {
                    b.HasOne("Car.API.Models.CarBodyType", "CarBodyTypeNavigation")
                        .WithMany("CarSeries")
                        .HasForeignKey("CarBodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_body_type_serie");

                    b.HasOne("Car.API.Models.CarGeneration", "CarGenerationNavigation")
                        .WithMany("CarSeries")
                        .HasForeignKey("CarGenerationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_car_generation_serie");

                    b.HasOne("Car.API.Models.CarModel", "CarModelNavigation")
                        .WithMany("CarSeries")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_model_serie");

                    b.HasOne("Car.API.Models.CarType", "CarTypeNavigation")
                        .WithMany("CarSeries")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_type_serie");

                    b.Navigation("CarBodyTypeNavigation");

                    b.Navigation("CarGenerationNavigation");

                    b.Navigation("CarModelNavigation");

                    b.Navigation("CarTypeNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarBodyType", b =>
                {
                    b.Navigation("CarSeries");
                });

            modelBuilder.Entity("Car.API.Models.CarBrand", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("Car.API.Models.CarCharacteristic", b =>
                {
                    b.Navigation("CarCharacteristicValues");

                    b.Navigation("InverseParentNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarDriveType", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("Car.API.Models.CarEngineType", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("Car.API.Models.CarEquipment", b =>
                {
                    b.Navigation("CarOptionValues");
                });

            modelBuilder.Entity("Car.API.Models.CarGeneration", b =>
                {
                    b.Navigation("CarSeries");
                });

            modelBuilder.Entity("Car.API.Models.CarModel", b =>
                {
                    b.Navigation("CarGenerations");

                    b.Navigation("CarModifications");

                    b.Navigation("CarSeries");
                });

            modelBuilder.Entity("Car.API.Models.CarModification", b =>
                {
                    b.Navigation("CarCharacteristicValues");

                    b.Navigation("CarEquipment");
                });

            modelBuilder.Entity("Car.API.Models.CarOption", b =>
                {
                    b.Navigation("CarOptionValues");

                    b.Navigation("InverseParentNavigation");
                });

            modelBuilder.Entity("Car.API.Models.CarSerie", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("Car.API.Models.CarTransmissionType", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("Car.API.Models.CarType", b =>
                {
                    b.Navigation("CarBrands");

                    b.Navigation("CarCharacteristicValues");

                    b.Navigation("CarCharacteristics");

                    b.Navigation("CarEquipments");

                    b.Navigation("CarGenerations");

                    b.Navigation("CarModels");

                    b.Navigation("CarModifications");

                    b.Navigation("CarOptionValues");

                    b.Navigation("CarOptions");

                    b.Navigation("CarSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
