// <auto-generated />
using Car.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car.Infrastructure.Migrations
{
    [DbContext(typeof(CarInfoDbContext))]
    [Migration("20250509005741_FixYearBeginType")]
    partial class FixYearBeginType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Car.Domain.Entities.CarBodyType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_body_type", (string)null);
                });

            modelBuilder.Entity("Car.Domain.Entities.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_brand", null, t =>
                        {
                            t.HasComment("Марки автомобилей");
                        });
                });

            modelBuilder.Entity("Car.Domain.Entities.CarColor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("ID цвета");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название цвета");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_color", null, t =>
                        {
                            t.HasComment("Цвета автомобилей");
                        });
                });

            modelBuilder.Entity("Car.Domain.Entities.CarCondition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("ID состояния авто");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название состояния");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_condition", null, t =>
                        {
                            t.HasComment("Состояние автомобилей");
                        });
                });

            modelBuilder.Entity("Car.Domain.Entities.CarDriveType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_drive_type", (string)null);
                });

            modelBuilder.Entity("Car.Domain.Entities.CarEngineType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_engine_type", (string)null);
                });

            modelBuilder.Entity("Car.Domain.Entities.CarGeneration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CarModelId")
                        .HasColumnType("int")
                        .HasColumnName("car_model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("YearBegin")
                        .HasColumnType("int")
                        .HasColumnName("year_begin");

                    b.Property<int?>("YearEnd")
                        .HasColumnType("int")
                        .HasColumnName("year_end");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarModelId" }, "id_car_model");

                    b.ToTable("car_generation", (string)null);
                });

            modelBuilder.Entity("Car.Domain.Entities.CarInteriorColor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("ID цвета салона");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название цвета салона");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_interior_color", null, t =>
                        {
                            t.HasComment("Цвета салона автомобилей");
                        });
                });

            modelBuilder.Entity("Car.Domain.Entities.CarInteriorMaterial", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("ID материала салона");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Название материала салона");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_interior_material", null, t =>
                        {
                            t.HasComment("Материалы салона автомобилей");
                        });
                });

            modelBuilder.Entity("Car.Domain.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("ID");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int")
                        .HasColumnName("car_brand_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarBrandId" }, "id_car_mark");

                    b.HasIndex(new[] { "Name" }, "name");

                    b.ToTable("car_model", null, t =>
                        {
                            t.HasComment("Модели автомобилей");
                        });
                });

            modelBuilder.Entity("Car.Domain.Entities.CarModification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("ID");

                    b.Property<int>("CarBodyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("car_body_type_id");

                    b.Property<int?>("CarDriveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("car_drive_type_id");

                    b.Property<int?>("CarEngineTypeId")
                        .HasColumnType("int")
                        .HasColumnName("car_engine_type_id");

                    b.Property<int>("CarGenerationId")
                        .HasColumnType("int")
                        .HasColumnName("car_generation_id");

                    b.Property<int?>("CarTransmissionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("car_transmission_type_id");

                    b.Property<int?>("EngineCapacity")
                        .HasColumnType("int")
                        .HasColumnName("engine_capacity");

                    b.Property<int?>("EnginePower")
                        .HasColumnType("int")
                        .HasColumnName("engine_power");

                    b.Property<decimal?>("FuelConsumptionCombined")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("fuel_consumption_combined");

                    b.Property<decimal?>("GroundClearance")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ground_clearance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarBodyTypeId" }, "fk_car_modification_car_body_type1_idx");

                    b.HasIndex(new[] { "CarGenerationId" }, "fk_car_modification_car_generation1_idx");

                    b.HasIndex(new[] { "CarDriveTypeId" }, "id_car_drive_type");

                    b.HasIndex(new[] { "CarEngineTypeId" }, "id_car_engine_type");

                    b.HasIndex(new[] { "CarTransmissionTypeId" }, "id_car_transmission_type");

                    b.ToTable("car_modification", null, t =>
                        {
                            t.HasComment("Модификации автомобилей");
                        });
                });

            modelBuilder.Entity("Car.Domain.Entities.CarTransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("car_transmission_type", (string)null);
                });

            modelBuilder.Entity("Car.Domain.Entities.CarGeneration", b =>
                {
                    b.HasOne("Car.Domain.Entities.CarModel", "CarModel")
                        .WithMany("CarGenerations")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_generation_id_car_model");

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarModel", b =>
                {
                    b.HasOne("Car.Domain.Entities.CarBrand", "CarBrand")
                        .WithMany("CarModels")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_model_id_car_mark");

                    b.Navigation("CarBrand");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarModification", b =>
                {
                    b.HasOne("Car.Domain.Entities.CarBodyType", "CarBodyType")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarBodyTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_car_modification_car_body_type1");

                    b.HasOne("Car.Domain.Entities.CarDriveType", "CarDriveType")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarDriveTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_car_drive_type");

                    b.HasOne("Car.Domain.Entities.CarEngineType", "CarEngineType")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarEngineTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_car_engine_type");

                    b.HasOne("Car.Domain.Entities.CarGeneration", "CarGeneration")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarGenerationId")
                        .IsRequired()
                        .HasConstraintName("fk_car_modification_car_generation1");

                    b.HasOne("Car.Domain.Entities.CarTransmissionType", "CarTransmissionType")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarTransmissionTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_car_transmission_type");

                    b.Navigation("CarBodyType");

                    b.Navigation("CarDriveType");

                    b.Navigation("CarEngineType");

                    b.Navigation("CarGeneration");

                    b.Navigation("CarTransmissionType");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarBodyType", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarBrand", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarDriveType", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarEngineType", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarGeneration", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarModel", b =>
                {
                    b.Navigation("CarGenerations");
                });

            modelBuilder.Entity("Car.Domain.Entities.CarTransmissionType", b =>
                {
                    b.Navigation("CarModifications");
                });
#pragma warning restore 612, 618
        }
    }
}
