// <auto-generated />
using System;
using Advert.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Advert.Infrastructure.Migrations
{
    [DbContext(typeof(AdvertDbContext))]
    partial class AdvertDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Advert.Domain.Entities.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("advert_category_id");

                    b.Property<uint>("AdvertPrivateStatusId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("advert_private_status_id");

                    b.Property<uint>("AdvertPublicStatusId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("advert_public_status_id");

                    b.Property<string>("AdvertStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("advert_status");

                    b.Property<string>("AdvertType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("advert_type");

                    b.Property<int>("DaysOnSale")
                        .HasColumnType("int")
                        .HasColumnName("days_on_sale");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("NextRefreshAvailableAt")
                        .HasColumnType("datetime")
                        .HasColumnName("next_refresh_available_at");

                    b.Property<int>("PlaceCityId")
                        .HasColumnType("int")
                        .HasColumnName("place_city_id");

                    b.Property<int?>("PlaceCountryId")
                        .HasColumnType("int")
                        .HasColumnName("place_country_id");

                    b.Property<int>("PlaceRegionId")
                        .HasColumnType("int")
                        .HasColumnName("place_region_id");

                    b.Property<int>("PriceAmount")
                        .HasColumnType("int")
                        .HasColumnName("price_amount");

                    b.Property<int>("PriceCurrency")
                        .HasColumnType("int")
                        .HasColumnName("price_currency");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("properties");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("published_at");

                    b.Property<DateTime>("RefreshedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("refreshed_at");

                    b.Property<string>("RemoveReason")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("remove_reason");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("seller_name");

                    b.Property<int>("TodayViews")
                        .HasColumnType("int")
                        .HasColumnName("today_views");

                    b.Property<int>("TotalBookmarks")
                        .HasColumnType("int")
                        .HasColumnName("total_bookmarks");

                    b.Property<int>("TotalPhoneViews")
                        .HasColumnType("int")
                        .HasColumnName("total_phone_views");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int")
                        .HasColumnName("total_views");

                    b.Property<int>("TotalVinViews")
                        .HasColumnType("int")
                        .HasColumnName("total_vin_views");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdvertCategoryId" }, "fk_advert_advert_category_idx");

                    b.HasIndex(new[] { "AdvertPrivateStatusId" }, "fk_advert_advert_private_status_idx");

                    b.HasIndex(new[] { "AdvertPublicStatusId" }, "fk_advert_advert_public_status1_idx");

                    b.HasIndex(new[] { "PlaceCountryId" }, "fk_advert_places1_idx");

                    b.HasIndex(new[] { "PlaceRegionId" }, "fk_advert_places2_idx");

                    b.HasIndex(new[] { "PlaceCityId" }, "fk_advert_places3_idx");

                    b.ToTable("advert", (string)null);
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("advert_category", (string)null);
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertPhoneNumber", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<int>("AdvertId")
                        .HasColumnType("int")
                        .HasColumnName("advert_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<int>("PhoneCodeId")
                        .HasColumnType("int")
                        .HasColumnName("phone_code_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdvertId" }, "fk_advert_phone_number_advert1_idx");

                    b.HasIndex(new[] { "PhoneCodeId" }, "fk_advert_phone_number_phone_code1_idx");

                    b.ToTable("advert_phone_number", (string)null);
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertPhoto", b =>
                {
                    b.Property<int>("AdvertId")
                        .HasColumnType("int")
                        .HasColumnName("advert_id");

                    b.Property<int>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsMain")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_main");

                    b.HasKey("AdvertId", "FileId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "AdvertId" }, "fk_advert_photo_advert1_idx");

                    b.ToTable("advert_photo", (string)null);
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertPrivateStatus", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoLabel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo_label");

                    b.Property<bool>("Published")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("published");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("advert_private_status", (string)null);
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertPublicStatus", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("advert_public_status", (string)null);
                });

            modelBuilder.Entity("Advert.Domain.Entities.PhoneCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("emoji");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("phone_code", (string)null);
                });

            modelBuilder.Entity("Advert.Domain.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseLabel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("case_label");

                    b.Property<string>("CaseLabelBel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("case_label_bel");

                    b.Property<string>("Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("emoji");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("label");

                    b.Property<string>("LabelBel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("label_bel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("short_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('country','region','city')")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ParentId" }, "parent_id");

                    b.ToTable("place", (string)null);
                });

            modelBuilder.Entity("Advert.Domain.Entities.Advert", b =>
                {
                    b.HasOne("Advert.Domain.Entities.AdvertCategory", "AdvertCategory")
                        .WithMany("Adverts")
                        .HasForeignKey("AdvertCategoryId")
                        .IsRequired()
                        .HasConstraintName("fk_advert_advert_category");

                    b.HasOne("Advert.Domain.Entities.AdvertPrivateStatus", "AdvertPrivateStatus")
                        .WithMany("Adverts")
                        .HasForeignKey("AdvertPrivateStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advert_advert_private_status");

                    b.HasOne("Advert.Domain.Entities.AdvertPublicStatus", "AdvertPublicStatus")
                        .WithMany("Adverts")
                        .HasForeignKey("AdvertPublicStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advert_advert_public_status");

                    b.HasOne("Advert.Domain.Entities.Place", "PlaceCity")
                        .WithMany("AdvertPlaceCities")
                        .HasForeignKey("PlaceCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advert_places3");

                    b.HasOne("Advert.Domain.Entities.Place", "PlaceCountry")
                        .WithMany("AdvertPlaceCountries")
                        .HasForeignKey("PlaceCountryId")
                        .HasConstraintName("fk_advert_places1");

                    b.HasOne("Advert.Domain.Entities.Place", "PlaceRegion")
                        .WithMany("AdvertPlaceRegions")
                        .HasForeignKey("PlaceRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advert_places2");

                    b.Navigation("AdvertCategory");

                    b.Navigation("AdvertPrivateStatus");

                    b.Navigation("AdvertPublicStatus");

                    b.Navigation("PlaceCity");

                    b.Navigation("PlaceCountry");

                    b.Navigation("PlaceRegion");
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertPhoneNumber", b =>
                {
                    b.HasOne("Advert.Domain.Entities.Advert", "Advert")
                        .WithMany("AdvertPhoneNumbers")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_advert_phone_number_advert1");

                    b.HasOne("Advert.Domain.Entities.PhoneCode", "PhoneCode")
                        .WithMany("AdvertPhoneNumbers")
                        .HasForeignKey("PhoneCodeId")
                        .IsRequired()
                        .HasConstraintName("fk_advert_phone_number_phone_code1");

                    b.Navigation("Advert");

                    b.Navigation("PhoneCode");
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertPhoto", b =>
                {
                    b.HasOne("Advert.Domain.Entities.Advert", "Advert")
                        .WithMany("AdvertPhotos")
                        .HasForeignKey("AdvertId")
                        .IsRequired()
                        .HasConstraintName("fk_advert_photo_advert1");

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Advert.Domain.Entities.Place", b =>
                {
                    b.HasOne("Advert.Domain.Entities.Place", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Advert.Domain.Entities.Advert", b =>
                {
                    b.Navigation("AdvertPhoneNumbers");

                    b.Navigation("AdvertPhotos");
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertCategory", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertPrivateStatus", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Advert.Domain.Entities.AdvertPublicStatus", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Advert.Domain.Entities.PhoneCode", b =>
                {
                    b.Navigation("AdvertPhoneNumbers");
                });

            modelBuilder.Entity("Advert.Domain.Entities.Place", b =>
                {
                    b.Navigation("AdvertPlaceCities");

                    b.Navigation("AdvertPlaceCountries");

                    b.Navigation("AdvertPlaceRegions");

                    b.Navigation("InverseParent");
                });
#pragma warning restore 612, 618
        }
    }
}
